export default {
  isGlobalNavigationVisible: false,
  comicsLatest: [],
  comicsBest: [],
  currentUser: {
    status: null,
    id: null,
    password: null,
    name: null,
    descriptions: null,
    email: null,
    site: null,
    imageUrl: null,
    createdAt: null,
    dropAt: null,
    comics: [],
    cuts: [],
    likes: [],
    likeUsers: [],
    likeComics: [],
    likeCuts: []
  },
  currentCut: {
    siblings: [],
    parent: null,
    child: null
  },
  user: {
    status: null,
    id: null,
    password: null,
    name: null,
    descriptions: null,
    email: null,
    site: null,
    imageUrl: null,
    createdAt: null,
    dropAt: null,
    comics: [],
    cuts: [],
    likes: [],
    likeUsers: [],
    likeComics: [],
    likeCuts: []
  },
  comic: {
    status: null,
    id: null,
    ownerId: null,
    owner: null,
    title: null,
    descriptions: null,
    imageUrl: null,
    createdAt: null,
    updatedAt: null,
    cuts: [],
    likes: []
  },
  cut: {
    status: null,
    id: null,
    ownerId: null,
    comicId: null,
    parentId: null,
    title: null,
    descriptions: null,
    imageUrl: null,
    createdAt: null,
    likes: []
  },
  tree: {}
}
